### ISSUE TITLE
perent id error

### ISSUE THREAD

**Issue by mak1986** [fortunejs/fortune-postgres#10]
Hi

I'm getting an error for doing this.

```javascript 
store.defineType('accommodation', {
	parent: { link: 'accommodation' },
	name: { type : String},
	description: { type: String }
});
```

Is this feature not included?

**Comment by 0x8890** [comment]
Can you show the error stack trace?

**Comment by mak1986** [comment]
```
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
Endpoints server is listening on port 4000...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at /home/makjacobsen/sandbox/beemodo-endpoints/index.js:46:9
    at tryCatcher (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/makjacobsen/sandbox/beemodo-endpoints/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[nodemon] app crashed - waiting for file changes before starting...


```

**Comment by 0x8890** [comment]
Looks like you have something else running on port 4000 and it's unrelated to this project :^)

**Comment by mak1986** [comment]
I haven't opened or closed any program and now when I run fortune again everything is fine. 
The strange thing was it failed when the parent id is included and worked when I delete it.  I tried this 3 times :/

**Comment by mak1986** [comment]
Thanks :)

**Comment by 0x8890** [comment]
FYI, the tests cover linking to the same type quite well: https://github.com/fortunejs/fortune/blob/master/test/integration/test_instance.js

**Comment by mak1986** [comment]
Found the reason. Nodemon is actually starting the fortune as a background process every i save the file.
